/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("app.kotlin-common-conventions")
}

dependencies {
    implementation(project(":shared"))
}

application {
    // Define the main class for the application.
    mainClass.set("app.client.MainKt")
}
